[package]
name = "mamut-diverter"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mamut-core = { path = "../mamut-core" }
tokio = { workspace = true }
thiserror = { workspace = true }
